spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      ddl-auto: create
      hibernate:
        generate_statistics: true
        format_sql: true
        dialect: ${DB_DIALECT}