server:
  port: 8081

application-name: ESM application Mail Sender
title: ESM application Mail sender APIs
version: 0.1.0
description: APIs description
base-package: com.epam.mailsender.controller
contact-name: Nodir Umarov
contact-email: mr.umarov.1995@gmail.com
git-url: https://github.com/NodirUmarov/epam-task-3/tree/main

springfox:
  documentation:
    swagger-ui:
      enabled: true