server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${DEV_DB_DRIVER}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    url: ${DEV_DB_URL}
  messages:
    basename: lang
    use-code-as-default-message: true
    encoding: UTF-8

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        dialect: ${DEV_DB_DIALECT}
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: create

app:
  scheduling:
    enable: false

application:
  default-locale: en_US

application-name: ESM application
title: ESM application APIs
version: 0.1.0
description: APIs description
base-package: com.epam.api.controller
contact-name: Nodir Umarov
contact-email: mr.umarov.1995@gmail.com
git-url: https://github.com/NodirUmarov/epam-task-3/tree/main

logging:
  level:
    root: WARN
    com:
      epam: TRACE