server:
  port: 8080

spring:
  datasource:
    driver-class-name: ${DEV_DB_DRIVER}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    url: ${DEV_DB_URL}


  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      ddl-auto: create
      hibernate:
        generate_statistics: true
        format_sql: true
        dialect: ${DEV_DB_DIALECT}
        enable_lazy_load_no_trans: true

logging:
  level:
    root: WARN
    com:
      epam: TRACE